version: '3.4'

services:
  frontend:
    image: fyusufa/matcha_frontend
    ports:
      - ${FRONTEND_PORT}:80
      # the following port is necessary for vite hot module reload (HMR)
      - 4443:4443
    volumes:
      - ./frontend:/app
    environment:
      VITE_BACKEND_HOST: ${BACKEND_HOST}
      VITE_BACKEND_PORT: ${BACKEND_PORT}
    build:
      context: ./frontend
      dockerfile: ${FRONTEND_DOCKERFILE}
      args:
          NODE_IMAGE: ${NODE_IMAGE}
    restart: unless-stopped
    depends_on:
      - backend
  backend:
    image: fyusufa/matcha_backend
    ports:
      - ${BACKEND_PORT}:4567
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_AUTO_RECONNECT: 'true'
      AUTH_JWT_SECRET: ${BACKEND_JWT_SECRET}
      AUTH_JWT_EXPIRATION: PT15M
      AUTH_REFRESH_TOKEN_EXPIRATION: P3D
      MAIL_AUTH_EMAIL: ${BACKEND_MAIL}
      MAIL_AUTH_PASSWORD: ${BACKEND_MAIL_PASSWORD}
    build:
      context: ./backend
      dockerfile: ${BACKEND_DOCKERFILE}
    restart: unless-stopped
    depends_on:
      - mysql
  mysql:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_HOST: localhost
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./database/server.cnf:/etc/mysql/conf.d/server.cnf
      - ./database/create.sql:/docker-entrypoint-initdb.d/create.sql
  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - 8888:80
    environment:
      PMA_HOST: mysql
      PMA_USER: ${DATABASE_USER}
      PMA_PASSWORD: ${DATABASE_PASSWORD}
    depends_on:
      - mysql
    profiles: ["debug"]

volumes:
  mysql-data:
