version: '3.4'

services:
  db:
    image: mysql
    restart: unless-stopped
    environment:
      # MYSQL_ROOT_HOST: localhost
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      # MYSQL_RANDOM_ROOT_PASSWORD: yes
      # MYSQL_USER: ${DB_USER}
      # MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - mysql-data:/var/lib/mysql
  frontend:
    image: fyusufa/matcha_frontend
    ports:
      - ${FRONTEND_PORT}:80
      # the following port is necessary for vite hot module reload (HMR)
      - 4443:4443
    volumes:
      - ./frontend:/app
    environment:
      VITE_BACKEND_HOST: ${BACKEND_HOST}
      VITE_BACKEND_PORT: ${BACKEND_PORT}
    build:
      context: .
      dockerfile: frontend/${FRONTEND_DOCKERFILE}
      args:
          NODE_IMAGE: ${NODE_IMAGE}
    restart: unless-stopped
    #    depends_on:
    #      - backend
  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - 8888:80
    environment:
      PMA_HOST: db
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
    profiles: ["debug"]

volumes:
  mysql-data:
