version: '3.4'

services:
  frontend:
    image: fyusufa/matcha_frontend
    ports:
      - ${FRONTEND_PORT}:80
      # the following port is necessary for vite hot module reload (HMR)
      - 4443:4443
    volumes:
      - ./frontend:/app
    environment:
      VITE_BACKEND_HOST: ${BACKEND_HOST}
      VITE_BACKEND_PORT: ${BACKEND_PORT}
    build:
      context: ./frontend
      dockerfile: ${FRONTEND_DOCKERFILE}
      args:
          NODE_IMAGE: ${NODE_IMAGE}
    restart: unless-stopped
    depends_on:
      - backend
  backend:
    image: fyusufa/matcha_backend
    ports:
      - ${BACKEND_PORT}:4567
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USER: ${DB_USER}
      DATABASE_PASSWORD: ${DB_PASSWORD}
      DATABASE_DATABASE: ${DB_DATABASE}
      DATABASE_AUTO_RECONNECT: 'true'
      AUTH_JWT_SECRET: ${BACKEND_JWT_SECRET}
      AUTH_JWT_EXPIRATION: PT15M
      AUTH_REFRESH_TOKEN_LENGTH: ${BACKEND_TOKEN_LENGTH}
      AUTH_REFRESH_TOKEN_EXPIRATION: P3D
      MAIL_HOST: ${BACKEND_MAIL_HOST}
      MAIL_PORT: ${BACKEND_MAIL_PORT}
      MAIL_AUTH: 'true'
      MAIL_SSL: 'true'
      MAIL_DEBUG: ${BACKEND_MAIL_DEBUG}
      MAIL_AUTH_EMAIL: ${BACKEND_MAIL}
      MAIL_AUTH_PASSWORD: ${BACKEND_MAIL_PASSWORD}
      MAIL_SENDER: ${BACKEND_MAIL}
    build:
      context: ./backend
      dockerfile: ${BACKEND_DOCKERFILE}
    restart: unless-stopped
    depends_on:
      - db
  db:
    image: fyusufa/matcha_mysql
    build:
      context: ./db
      dockerfile: ${BACKEND_DOCKERFILE}
    restart: unless-stopped
    environment:
      MYSQL_ROOT_HOST: localhost
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db/01-setup.sh:/docker-entrypoint-initdb.d/01-setup.sh
      - ./db/server.cnf:/etc/mysql/conf.d/server.cnf
  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - 8888:80
    environment:
      PMA_HOST: db
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
    profiles: ["debug"]

volumes:
  mysql-data:
