/* tslint:disable */
/* eslint-disable */
/**
 * Matcha
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Heartbeat
 */
export interface Heartbeat {
    /**
     * 
     * @type {number}
     * @memberof Heartbeat
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Heartbeat
     */
    ip?: string;
    /**
     * 
     * @type {number}
     * @memberof Heartbeat
     */
    latitude?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Heartbeat
     */
    longitude?: number | null;
    /**
     * 
     * @type {string}
     * @memberof Heartbeat
     */
    city?: string;
    /**
     * 
     * @type {string}
     * @memberof Heartbeat
     */
    country?: string;
    /**
     * 
     * @type {Date}
     * @memberof Heartbeat
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Heartbeat
     */
    updatedAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof Heartbeat
     */
    userId?: number;
}
