/* tslint:disable */
/* eslint-disable */
/**
 * Matcha
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import type { NotificationType } from './notification-type';
/**
 * 
 * @export
 * @interface Notification
 */
export interface Notification {
    /**
     * 
     * @type {number}
     * @memberof Notification
     */
    id?: number;
    /**
     * 
     * @type {NotificationType}
     * @memberof Notification
     */
    type?: NotificationType;
    /**
     * 
     * @type {string}
     * @memberof Notification
     */
    content?: string;
    /**
     * 
     * @type {string}
     * @memberof Notification
     */
    link?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Notification
     */
    read?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof Notification
     */
    readAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Notification
     */
    createdAt?: Date;
}
