/* tslint:disable */
/* eslint-disable */
/**
 * Matcha
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import type { PresenceAvailability } from './presence-availability';
/**
 * 
 * @export
 * @interface Presence
 */
export interface Presence {
    /**
     * 
     * @type {PresenceAvailability}
     * @memberof Presence
     */
    availability?: PresenceAvailability;
    /**
     * 
     * @type {Date}
     * @memberof Presence
     */
    since?: Date;
}
