/* tslint:disable */
/* eslint-disable */
/**
 * Matcha
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface RegisterForm
 */
export interface RegisterForm {
    /**
     * 
     * @type {string}
     * @memberof RegisterForm
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterForm
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterForm
     */
    login?: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterForm
     */
    password?: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterForm
     */
    email?: string;
}
