/* tslint:disable */
/* eslint-disable */
/**
 * Matcha
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import type { Tag } from './tag';
/**
 * 
 * @export
 * @interface TagPage
 */
export interface TagPage {
    /**
     * 
     * @type {Array<Tag>}
     * @memberof TagPage
     */
    content?: Array<Tag>;
    /**
     * 
     * @type {number}
     * @memberof TagPage
     */
    totalElements?: number;
    /**
     * 
     * @type {boolean}
     * @memberof TagPage
     */
    first?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TagPage
     */
    last?: boolean;
    /**
     * 
     * @type {number}
     * @memberof TagPage
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof TagPage
     */
    totalPages?: number;
    /**
     * 
     * @type {number}
     * @memberof TagPage
     */
    pageNumber?: number;
}
