/* tslint:disable */
/* eslint-disable */
/**
 * Matcha
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import type { Gender } from './gender';
import type { LocationDto } from './location-dto';
import type { PictureDto } from './picture-dto';
import type { Presence } from './presence';
import type { RelationshipDto } from './relationship-dto';
import type { SexualOrientation } from './sexual-orientation';
/**
 * 
 * @export
 * @interface UserDto
 */
export interface UserDto {
    /**
     * 
     * @type {number}
     * @memberof UserDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    login?: string;
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    biography?: string;
    /**
     * 
     * @type {Gender}
     * @memberof UserDto
     */
    gender?: Gender;
    /**
     * 
     * @type {SexualOrientation}
     * @memberof UserDto
     */
    sexualOrientation?: SexualOrientation;
    /**
     * 
     * @type {number}
     * @memberof UserDto
     */
    fame?: number;
    /**
     * 
     * @type {boolean}
     * @memberof UserDto
     */
    emailConfirmed?: boolean;
    /**
     * 
     * @type {PictureDto}
     * @memberof UserDto
     */
    picture?: PictureDto;
    /**
     * 
     * @type {RelationshipDto}
     * @memberof UserDto
     */
    relationship?: RelationshipDto;
    /**
     * 
     * @type {LocationDto}
     * @memberof UserDto
     */
    location?: LocationDto;
    /**
     * 
     * @type {Presence}
     * @memberof UserDto
     */
    presence?: Presence;
}
