/* tslint:disable */
/* eslint-disable */
/**
 * Matcha
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import type { UserDto } from './user-dto';
/**
 * 
 * @export
 * @interface VisitDto
 */
export interface VisitDto {
    /**
     * 
     * @type {number}
     * @memberof VisitDto
     */
    id?: number;
    /**
     * 
     * @type {UserDto}
     * @memberof VisitDto
     */
    user?: UserDto;
    /**
     * 
     * @type {string}
     * @memberof VisitDto
     */
    date?: string;
    /**
     * 
     * @type {number}
     * @memberof VisitDto
     */
    times?: number;
    /**
     * 
     * @type {string}
     * @memberof VisitDto
     */
    firstAt?: string;
    /**
     * 
     * @type {string}
     * @memberof VisitDto
     */
    lastAt?: string;
}
