/* tslint:disable */
/* eslint-disable */
/**
 * Matcha
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import type { VisitDto } from './visit-dto';
/**
 * 
 * @export
 * @interface VisitDtoPage
 */
export interface VisitDtoPage {
    /**
     * 
     * @type {Array<VisitDto>}
     * @memberof VisitDtoPage
     */
    content?: Array<VisitDto>;
    /**
     * 
     * @type {number}
     * @memberof VisitDtoPage
     */
    totalElements?: number;
    /**
     * 
     * @type {boolean}
     * @memberof VisitDtoPage
     */
    first?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof VisitDtoPage
     */
    last?: boolean;
    /**
     * 
     * @type {number}
     * @memberof VisitDtoPage
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof VisitDtoPage
     */
    totalPages?: number;
    /**
     * 
     * @type {number}
     * @memberof VisitDtoPage
     */
    pageNumber?: number;
}
